### ISSUE TITLE
Can't find where to set permission roles

### ISSUE THREAD

**Issue by Nerothos** [erichard/ErichardDmsBundle#25]
Hi,
Sorry to post this in a issue. I'm a beginner with all symfony "external" bundle stuff and I have a problem when I try to setup this bundle.
After making the README configuration, This following error show up :

>The DMS need to know which roles it can use. Please configure 'erichard_dms.permission.roles' or 'erichard_dms.permission.role_provider.

I have try to add a "role" or "permission.role" or even "permission" in security.yml and services.yml but the parameter is not recognized.

Can you guide me on how can I set this option? For information, I don't use FOSUserBundle to manage user.
And maybe adding it to the README for further use ^^'

**Comment by erichard** [comment]
Hi,

You need to add a section in your config.yml. Something like this 

```
erichard_dms:
    permission:
        roles: [ROLE_ADMIN]
```

**Comment by Nerothos** [comment]
Thank you very much, it has solved this error.
